"""
This is a Qwen2.5 LLM class model.

Tested on 3B & 7B Instruct GGUF models.

The tool call function happens in the content object and
LangGraph usually does not handle it.

When tool have args:
<tool_call>\n{{"name": "...", "arguments": { "arg1": "...", "arg2": "..." }}}}\n</tool_call>

but the number of '}' will vary each query so dynamic checking is necessary

When tool have no args:
<tool_call>\n{{"name": "...", "arguments": {}}}}\n</tool_call>
"""

import json
from typing import ClassVar, override

from langchain_core.messages import AIMessage
from structures.interfaces.tool import ToolStatusType
from structures.llms.local_provider import (
    LocalProvider,
)


class Qwen25(LocalProvider):
    """Qwen2.5 instances for supported frameworks.

    Provides a way to format tool call tags to be used by MCP server

    For all supported args,
    see: https://python.langchain.com/api_reference/community/chat_models/langchain_community.chat_models.llamacpp.ChatLlamaCpp.html#
    see: https://llama-cpp-python.readthedocs.io/en/latest/api-reference/
    see: https://python.langchain.com/api_reference/openai/chat_models/langchain_openai.chat_models.base.ChatOpenAI.html

    """

    # Static/Macros
    """
    Due to varied opening and closing brackets, newline will be the starting index
    and decrement loop will be used
    """
    # start_tag: ClassVar[str] = "<tool_call>\n{"
    start_tag: ClassVar[str] = "<tool_call>\n"
    # end_tag: ClassVar[str] = "}}\n</tool_call>"
    end_tag: ClassVar[str] = "\n</tool_call>"

    @override
    def check_tool_tags(self, ai_message: str | list) -> ToolStatusType:
        """
        Processes AIMessage and to extract the tool call tags if any.

        There is an edge case (#E1) in the start and/or end tags of having varied number of
        brackets.

        Args:
            ai_message: A message string response generated by the LLM. List is
            accepted to support tool call for OpenAI compatibility.

        Returns:
            ToolStatusType: A tuple of boolean, tuple(int, int), tuple(int, int)
                First param is status if tool call tags are found.
                Second param is a tuple of start tool call tags with its head
                    and end indexes.
                Third param is a tuple of end tool call tags with its head and
                    end indexes.
        """
        # Handle remote LlamaCPP llm
        if type(ai_message) is list and ai_message:
            return ToolStatusType(True, None, None)

        # Handle local LlamaCPP llm
        if self.start_tag in ai_message and self.end_tag in ai_message:
            # # Handle #E1 different tag count
            # Dynamic check for start tags
            # This skips "\n" char
            start_head = ai_message.find(self.start_tag) + len(self.start_tag)
            bracket_count, min_bracket, excess_bracket = 0, 1, 0
            for i in range(start_head, len(ai_message)):
                if ai_message[i] == "{":
                    bracket_count += 1
                    continue
                break
            if bracket_count > min_bracket:
                excess_bracket = bracket_count - min_bracket
            start_tag_indexes = (
                ai_message.find(self.start_tag),
                start_head + excess_bracket,
            )

            # Dynamic check for end tags
            end_head = ai_message.find(self.end_tag)
            ## To skip "\n" new char
            bracket_count, min_bracket, excess_bracket = 0, 2, 0
            for i in range(end_head - 1, 0, -1):
                if ai_message[i] == "}":
                    bracket_count += 1
                    continue
                break
            if bracket_count > min_bracket:
                excess_bracket = bracket_count - min_bracket
            end_tag_indexes = (
                end_head - excess_bracket,
                end_head + len(self.end_tag) - 1,
            )

            return ToolStatusType(True, start_tag_indexes, end_tag_indexes)

        return ToolStatusType(False, None, None)

    @override
    def format_tool_message(
        self, id: str, ai_message: str | list, tool_info: ToolStatusType
    ) -> AIMessage:
        """
        Format the tool call message for LangGraph interpretation.

        Args:
            ai_message: A message string response generated by the LLM. List is
            accepted to support tool call for OpenAI compatibility.

        Returns:
            AIMessage instance that can be passed to LLM for tool calling.
        """
        # Slice from the end as they are still intact
        if tool_info.status is False:
            raise ValueError(
                "Tool Info object should not be False when formatting tool message."
            )
        if type(ai_message) is str:
            if tool_info.start_tag_indexes is None or tool_info.end_tag_indexes is None:
                raise ValueError("Start tag / End tag tuples should not be None.")
            format_message = ai_message[: tool_info.end_tag_indexes[0]]
            format_message = format_message[tool_info.start_tag_indexes[1] :]

        # TO FIX THIS: since only 1 tool call is accepted within the list
        # Below is sample output from OpenAI tool call
        # {'name': 'tool_name', 'args': { ... }, 'id': 'some_id', 'type': 'tool_call'}
        if type(ai_message) is list:
            # Change all single quote to double quotes for JSON decode
            format_message = json.dumps(ai_message[0])
            format_message = format_message.replace("args", "arguments")

        try:
            tool_obj = json.loads(format_message)
        except Exception as e:
            raise TypeError(f"Error converting message to tool object: {e}")

        msg_with_tools = AIMessage(
            content="",
            tool_calls=[
                {
                    "name": tool_obj["name"],
                    "args": tool_obj["arguments"],
                    "id": id,
                    "type": "tool_call",
                },
            ],
        )
        return msg_with_tools
